### ISSUE TITLE
Add README.md (and Wiki pages ?)

### ISSUE THREAD

**Issue by JordanViknar** [Iltotore/cylang#29]
In a language that's meant to be accessible to teacher and students alike, particularly at CY Tech, I think it's important we should have at the very least a README.md that explains to people how CYLang should be ran, and eventually links to some notes about the syntax (the wiki feature of GitHub would be ideal for that). Perhaps, it should also specify caveats/bugs present in it, along with installation instructions if deemed necessary.

Also, we have to hold both an English version and a French version of the documentation for this project, since it's managed in English, and conceived for French students.

I'm usually pretty good at making README.md files, but for once, I cannot help much, because I do not know well enough about how CYLang works, apart from the syntax it relies on.

Anyways, I wish you good luck. Remember that for many of the students you're making this interpreter for, they have absolutely no idea what Scala is, some of them (at the start of a year) barely know anything other than Python, and a certain amount probably have a fear of terminals.

**Comment by Iltotore** [comment]
Closed in https://github.com/Iltotore/cylang/commit/cc594084e45988711827631dbb3206b170475ab3
